In [47]:
import pandas as pd
import numpy as np

Opening file

In [48]:
path='C:/Users/COMPUMARTS/Downloads/repo/Cafe data cleaning/cafe_sales.csv'
df=pd.read_csv(path)
# df.head(25)

Replace spaces in columns to avoid any errors

In [49]:
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['Transaction_ID', 'Item', 'Quantity', 'Price_Per_Unit', 'Total_Spent',
       'Payment_Method', 'Location', 'Transaction_Date'],
      dtype='object')

### Null count for each column

In [50]:
df.isna().sum()

Transaction_ID         0
Item                 333
Quantity             138
Price_Per_Unit       179
Total_Spent          173
Payment_Method      2579
Location            3265
Transaction_Date     159
dtype: int64

### Now Standardizing all null values

In [51]:
df = df.replace({'UNKNOWN':pd.NA, 'NaN':pd.NA , 'ERROR':pd.NA})
df.head()

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,<NA>,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<NA>,<NA>,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

### Fill the Quantity null values
    by dividing the Total_Spent in Price_Per_Unit
    to insure getting the right values

In [52]:
 #! we used pd.to_numeric instead of df.astype to avoid the problems that may happen cause of null values
df['Total_Spent'] = pd.to_numeric(df['Total_Spent'], errors='coerce')
df['Price_Per_Unit'] = pd.to_numeric(df['Price_Per_Unit'], errors='coerce')


df['Quantity'] = df.apply(# i here is a row in the data frame
    lambda i: i['Total_Spent']/i['Price_Per_Unit'] if pd.isna(i['Quantity']) else i['Quantity'],axis=1)
# df.head()

Here we try to fill up Total_Spent column after we filled quantity column

In [53]:
df['Quantity'] = df['Quantity'].astype('float')
df['Total_Spent']=df.apply(
    lambda i:i['Quantity']*i['Price_Per_Unit'] if pd.isna(i['Total_Spent']) else i['Total_Spent'],axis=1)
# df.tail(60)

Now we will try to fill Price_per_Unit after we filled Quantity and Total_Spent columns

In [54]:
df['Price_Per_Unit'] = df.apply(
	lambda row: row['Total_Spent']/row['Quantity'] if pd.isna(row['Price_Per_Unit']) else row['Price_Per_Unit'],
	axis=1
)
# df.tail(60)

In [55]:
df.isna().sum()

Transaction_ID         0
Item                 969
Quantity              38
Price_Per_Unit        38
Total_Spent           40
Payment_Method      3178
Location            3961
Transaction_Date     460
dtype: int64

To Check why some values are null

In [56]:
null_index = df[df['Price_Per_Unit'].isna()].index
print(df.isnull().sum())
for i in null_index:
    print(df.loc[i, ['Price_Per_Unit','Quantity','Total_Spent']])

Transaction_ID         0
Item                 969
Quantity              38
Price_Per_Unit        38
Total_Spent           40
Payment_Method      3178
Location            3961
Transaction_Date     460
dtype: int64
Price_Per_Unit    NaN
Quantity          3.0
Total_Spent       NaN
Name: 65, dtype: object
Price_Per_Unit     NaN
Quantity           NaN
Total_Spent       12.0
Name: 629, dtype: object
Price_Per_Unit     NaN
Quantity           NaN
Total_Spent       20.0
Name: 912, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       3.0
Name: 1008, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       6.0
Name: 1436, dtype: object
Price_Per_Unit     NaN
Quantity           NaN
Total_Spent       16.0
Name: 1482, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 1674, dtype: object
Price_Per_Unit    NaN
Quantity          4.0
Total_Spent       NaN
Name: 1761, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 2229, dtype: object
Price_Per_Unit    NaN
Quantity          4.0
Total_Spent       NaN
Name: 2289, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       5.0
Name: 2330, dtype: object
Price_Per_Unit    NaN
Quantity          3.0
Total_Spent       NaN
Name: 2585, dtype: object
Price_Per_Unit    NaN
Quantity          3.0
Total_Spent       NaN
Name: 3162, dtype: object
Price_Per_Unit    NaN
Quantity          1.0
Total_Spent       NaN
Name: 3598, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       1.0
Name: 3635, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 3673, dtype: object
Price_Per_Unit     NaN
Quantity           NaN
Total_Spent       25.0
Name: 3779, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 4021, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 4152, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       6.0
Name: 5639, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       8.0
Name: 5845, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       2.0
Name: 6225, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       1.0
Name: 6661, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       4.0
Name: 6674, dtype: object
Price_Per_Unit    NaN
Quantity          5.0
Total_Spent       NaN
Name: 7035, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 7230, dtype: object
Price_Per_Unit    NaN
Quantity          5.0
Total_Spent       NaN
Name: 7244, dtype: object
Price_Per_Unit    NaN
Quantity          5.0
Total_Spent       NaN
Name: 7568, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       9.0
Name: 7597, dtype: object
Price_Per_Unit    NaN
Quantity          5.0
Total_Spent       NaN
Name: 7686, dtype: object
Price_Per_Unit    NaN
Quantity          3.0
Total_Spent       NaN
Name: 8128, dtype: object
Price_Per_Unit    NaN
Quantity          3.0
Total_Spent       NaN
Name: 8497, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       3.0
Name: 8669, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       7.5
Name: 8975, dtype: object
Price_Per_Unit    NaN
Quantity          1.0
Total_Spent       NaN
Name: 9212, dtype: object
Price_Per_Unit    NaN
Quantity          NaN
Total_Spent       3.0
Name: 9464, dtype: object
Price_Per_Unit     NaN
Quantity           NaN
Total_Spent       20.0
Name: 9819, dtype: object
Price_Per_Unit    NaN
Quantity          2.0
Total_Spent       NaN
Name: 9893, dtype: object

To delete the null values that we can't find it

In [57]:
df=df.dropna(subset=['Quantity'])
df=df.dropna(subset=['Price_Per_Unit'])
df=df.dropna(subset=['Total_Spent'])
# print(df.isnull().sum())
df.shape

(9942, 8)

### Now replacing the null values in Payment_Method and Location with mode

In [58]:
P_mode=df['Payment_Method'].mode()[0]
df['Payment_Method'].fillna(P_mode,inplace=True)

L_mode=df['Location'].mode()[0]
df['Location'].fillna(L_mode,inplace=True)
print(df.isnull().sum())

Transaction_ID        0
Item                963
Quantity              0
Price_Per_Unit        0
Total_Spent           0
Payment_Method        0
Location              0
Transaction_Date    457
dtype: int64

C:\Users\COMPUMARTS\AppData\Local\Temp\ipykernel_1716\3132539126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Method'].fillna(P_mode,inplace=True)
C:\Users\COMPUMARTS\AppData\Local\Temp\ipykernel_1716\3132539126.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Location'].fillna(L_mode,inplace=True)

Now we will get the unique values in Item column to try to replace the null values in it

In [59]:
unique_items = df['Item'].unique()
unique_prices = df['Price_Per_Unit'].unique()
print(unique_items)
print(unique_prices)
# df[['Item','Price_Per_Unit']].head()

['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' <NA> 'Sandwich' nan 'Juice'
 'Tea']
[2.  3.  1.  5.  4.  1.5]

In [60]:
 #! cause of we have two products with the same price we replaced it with the mode
df.loc[df['Price_Per_Unit']==1.0,'Item']='Cookie'
df.loc[df['Price_Per_Unit']==1.5,'Item']='Tea'
df.loc[df['Price_Per_Unit']==2.0,'Item']='Coffee'
df.loc[df['Price_Per_Unit']==3.0,'Item']=df['Item'].mode()[0]
df.loc[df['Price_Per_Unit']==4.0,'Item']='Smoothie'
df.loc[df['Price_Per_Unit']==5.0,'Item']='Salad'
print(df.isna().sum())

Transaction_ID        0
Item                  0
Quantity              0
Price_Per_Unit        0
Total_Spent           0
Payment_Method        0
Location              0
Transaction_Date    457
dtype: int64

In [61]:
print(df.isna().sum())

Transaction_ID        0
Item                  0
Quantity              0
Price_Per_Unit        0
Total_Spent           0
Payment_Method        0
Location              0
Transaction_Date    457
dtype: int64

### Working with Dates

First, remove all null values in date

In [62]:
df=df.dropna(subset=['Transaction_Date'])

In [63]:
df['Transaction_Date'].isna().sum()

np.int64(0)

Second, add season column

In [64]:
# Change date format from --string-- to --date time--
df['Transaction_Date']=pd.to_datetime(df['Transaction_Date'])

In [65]:
df["season"] = np.select(
    [
        df['Transaction_Date'].dt.month.isin([12,1,2]),
        df['Transaction_Date'].dt.month.isin([3,4,5]),
        df['Transaction_Date'].dt.month.isin([6,7,8]),
        df['Transaction_Date'].dt.month.isin([9,10,11]),
    ],
    ["Winter", "Spring", "Summer", "Autumn"],
    default="Unknown"
)

In [66]:
df['season'].unique()

array(['Autumn', 'Spring', 'Summer', 'Winter'], dtype=object)

### Save Cleaned Date

In [67]:
df.to_csv('C:/Users/COMPUMARTS/Downloads/repo/Cafe data cleaning/clean_cafe_sales_saved.csv')

In [68]:
df.head(20)

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,season
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,Autumn
1,TXN_4977031,Coffee,4.0,3.0,12.0,Cash,In-store,2023-05-16,Spring
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,Summer
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27,Spring
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,Summer
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Takeaway,2023-03-31,Spring
6,TXN_4433211,Coffee,3.0,3.0,9.0,Digital Wallet,Takeaway,2023-10-06,Autumn
7,TXN_6699534,Smoothie,4.0,4.0,16.0,Cash,Takeaway,2023-10-28,Autumn
8,TXN_4717867,Coffee,5.0,3.0,15.0,Digital Wallet,Takeaway,2023-07-28,Summer
9,TXN_2064365,Smoothie,5.0,4.0,20.0,Digital Wallet,In-store,2023-12-31,Winter
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,Autumn
12,TXN_7619095,Smoothie,2.0,4.0,8.0,Cash,In-store,2023-05-03,Spring
13,TXN_9437049,Cookie,5.0,1.0,5.0,Digital Wallet,Takeaway,2023-06-01,Summer
14,TXN_8915701,Tea,2.0,1.5,3.0,Digital Wallet,In-store,2023-03-21,Spring
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,Autumn
16,TXN_3765707,Smoothie,1.0,4.0,4.0,Digital Wallet,Takeaway,2023-06-10,Summer
17,TXN_6769710,Coffee,2.0,3.0,6.0,Cash,In-store,2023-02-24,Winter
18,TXN_8876618,Coffee,5.0,3.0,15.0,Cash,Takeaway,2023-03-25,Spring
19,TXN_3709394,Coffee,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,Winter
20,TXN_3522028,Smoothie,5.0,4.0,20.0,Cash,In-store,2023-04-04,Spring

In [ ]:
df['Transaction_ID'].duplicated().sum()

np.int64(0)